### ISSUE TITLE
About D-MIL

### ISSUE THREAD

**Issue by PURE-melo** [vasgaowei/D-MIL.pytorch#3]
Hi~, thanks for your nice work. I have a little question. 
I can't find the specific paper for D-MIL. Can you tell me which wsod method does D-MIL refer to? Or is D-MIL an improved version of the official PCL code?

**Comment by vasgaowei** [comment]
The paper is still under review. And D-MIL is based on PCL.

**Comment by PURE-melo** [comment]
Thanks for your reply, I understand.
