### ISSUE TITLE
support Pytorch >=1.5

### ISSUE THREAD

**Issue by bityangke** [vasgaowei/D-MIL.pytorch#4]
Hi Wei,
How can D-MIL support Pytorch above 1.4?

**Comment by vasgaowei** [comment]
It's sorry that only pytorch 1.0 - 1.4 is supported now. And [branch](https://github.com/vasgaowei/D-MIL.pytorch/tree/detectron_wsod) supports pytorch above 1.4.

**Comment by bityangke** [comment]
Thanks！
